name: oscy
services:
  api:
    env_file:
      - .env
    environment:
      - PG_HOST=db
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/db.sql:/data/db.sql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    env_file:
      - .env
    environment:
      - API_HOST=api
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_started
volumes:
  db-data:
