name: oscy
services:
  api:
    env_file:
      - .env
    environment:
      - PG_HOST=db
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/db.dump:/data/db.dump
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    env_file:
      - .env
    environment:
      - LOCAL_API_HOST=api
    build:
      context: ./frontend
      args:
        - BUILD_LOCAL_API_HOST=api # overrides value in .env
      secrets:
        - build_env
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_started

secrets:
  build_env:
    file: .env

volumes:
  db-data:
